server:
  port : 8085
  servlet:
    context-path: /ms-tweet-service

spring:
  application:
    name: ms-tweet-service
  flyway:
    enabled: true
    baseline-on-migrate : true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
  #      This config will override the flyway because it will drop the user schema flyway
  #      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/ms_tweet_service
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver

google:
  api:
    url: https://www.googleapis.com/youtube/v3/videos?id=%s&key=%s&part=snippet,contentDetails,statistics,status
    key: AIzaSyAzjkMGVmYbeNnfkHFaViidfftvFot31lE

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${EUREKA_HOST:localhost}